### ISSUE TITLE
Error Just runnig it after install 

### ISSUE THREAD

**Issue by charesredhat** [aquilesb/v-datatable-light#11]
Hi I got the following the error after just running the instlall

 $ npm run serve

> v-datatable-light@0.5.0 serve /home/ec2-user/environment/edb.interface/v-datatable-light
> vue-cli-service serve ./example/main.js --open

/home/ec2-user/environment/edb.interface/v-datatable-light/node_modules/open/index.js:11
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/environment/edb.interface/v-datatable-light/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)

npm ERR! Linux 4.14.72-68.55.amzn1.x86_64
npm ERR! argv "/home/ec2-user/.nvm/versions/node/v6.14.4/bin/node" "/home/ec2-user/.nvm/versions/node/v6.14.4/bin/npm" "run" "serve"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! v-datatable-light@0.5.0 serve: `vue-cli-service serve ./example/main.js --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v-datatable-light@0.5.0 serve script 'vue-cli-service serve ./example/main.js --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v-datatable-light package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve ./example/main.js --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v-datatable-light
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v-datatable-light
npm ERR! There is likely additional logging output above.

**Comment by aquilesb** [comment]
Hi, which node version are you using? I have tested on v10.15.1 and everything worked fine.

**Comment by KelvinCampelo** [comment]
@charesredhat looks like you are using node v6.14.4, can you try to updated your node to a newer version like 9.x.x or 10.x.x? I recommend you to use [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md), so you can change the version of node when needed.

**Comment by charesredhat** [comment]
> @charesredhat looks like you are using node v6.14.4, can you try to updated your node to a newer version like 9.x.x or 10.x.x? I recommend you to use [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md), so you can change the version of node when needed.

Ok I will try to update my node version to v10 and get back to you thanks

**Comment by aquilesb** [comment]
@charesredhat Did you find the problem?
