### ISSUE TITLE
How to add another actions on same <td>?

### ISSUE THREAD

**Issue by benjielim** [aquilesb/v-datatable-light#18]
How to add another actions on same td?

**Comment by aquilesb** [comment]
Why would you need more than one action on the same td?

**Comment by benjielim** [comment]
I need it to be like this.
![Screen Shot 2019-07-08 at 6 02 42 PM](https://user-images.githubusercontent.com/52655825/60802056-ae29d480-a1aa-11e9-9d78-2aadab38ecb0.png)

**Comment by aquilesb** [comment]
You can use the same action to add as many components as you need using a wrapper component on the slot.

You can check that [here](https://gist.github.com/aquilesb/ec4c774fc0124a580d63c4deca5f1480)

**Comment by benjielim** [comment]
> You can use the same action to add as many components as you need using a wrapper component on the slot.
> 
> You can check that [here](https://gist.github.com/aquilesb/ec4c774fc0124a580d63c4deca5f1480)

Thank You!
