### ISSUE TITLE
Incompatible with Vue 2.6.XX

### ISSUE THREAD

**Issue by dlkulp** [aquilesb/v-datatable-light#19]
Looks like `slot-scope` and the method of binding properties has been deprecated as of Vue version 2.6.XX.  I'm having trouble figuring out how to access data passed into the actions slot when clicking a button.  The example provided does the following:

    <input
        slot="actions"
        slot-scope="props"
        type="button"
        class="btn btn-info"
        value="Edit"
        @click="dtEditClick(props);"
      >

For more info on the new way slots are handled, see this: [https://github.com/vuejs/rfcs/blob/master/active-rfcs/0001-new-slot-syntax.md](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0001-new-slot-syntax.md)

**Comment by dlkulp** [comment]
I think maybe this section: 

    <slot
        v-if="isFieldSpecial(key.name) && extractArgs(key.name) === 'actions'"
        :name="extractActionID(key.name)"
        :row-data="item"
        :row-index="index"
    />

should be:

    <slot
        v-if="isFieldSpecial(key.name)&&extractArgs(key.name) === 'actions'"
        v-bind:default="{'name':extractActionID(key.name), 'row-data': item, 'row-index': index}"
    />

Though I'm not entirely certain.  There may be a better way that would just allow me to access those props better on my side since `slot-scope="props"` no longer works.

**Comment by aquilesb** [comment]
Hey @dlkulp, you right, all the examples on the project still using the `slot-scope` on slots.
You can (should) use the new `v-slot` directive instead.
```
<template v-slot:actions="props">
   <input
        type="button"
        class="btn btn-info"
        value="Edit"
        @click="dtEditClick(props);" />
</template>
```
Just reminding, this was soft-deprecated in the 2.X versions, and only will be removed on 3.X version. That means you may still using the `slot-scope` while you are running on 2.X version

**Comment by dlkulp** [comment]
I think I realized that my issue was due to how I was wrapping the datatable component.  The combination of mixed syntax depending on where I looked and my lack of experience with slots didn't help either!  

Thanks!
