### ISSUE TITLE
column values - align

### ISSUE THREAD

**Issue by Hiroshana** [aquilesb/v-datatable-light#23]
Hi
I have used "v-datatable-light": "^0.8.0", for one of my projects. I am having small issue. Appreciate if you could help me to sort out the matter.
How I align the column values either left or right? Default all the cell values centre.

Thank you
Hiroshana

**Comment by aquilesb** [comment]
Hi, 
I believe right now we don't have anything to set a class for all cells for a specific column.
It is an interesting feature to add, I will try to take a look in the next days.
As a remedy for a while, you can try to use css.

`.v-datatable-light tbody tr td:nth-of-type(3) {
  text-align:left;
}`

As you can see [here](https://codepen.io/aquilesb/pen/wVaBPv)

**Comment by Hiroshana** [comment]
Thank you.

**Comment by Hiroshana** [comment]
Hello Aquiles Boff, 
Thank you, last time helping me to sort out alignment stuff in column using css but same issue in header. I have tried css for table header but it doesn't work for me. I much appreciate if you could help me and given an idea for how to align headers?
Here is css cording 

.mybillspayments .v-datatable-light thead tr th.header-item .th-wrapper:nth-of-type(1){
  justify-content: flex-end;
}

Thank you
Hiroshana
