### ISSUE TITLE
Hedder Align

### ISSUE THREAD

**Issue by Hiroshana** [aquilesb/v-datatable-light#24]
Hello Aquiles Boff,
Thank you, last time helping me to sort out alignment stuff in column using css but same issue in header. I have tried css for table header but it doesn't work for me. I much appreciate if you could help me and given an idea for how to align headers?
Here is css cording

.mybillspayments .v-datatable-light thead tr th.header-item .th-wrapper:nth-of-type(1){
justify-content: flex-end;
}

Thank you
Hiroshana

**Comment by aquilesb** [comment]
Hi Hirshana,

I think this should solve your problem for now:
`.v-datatable-light thead tr th.header-item:nth-of-type(4) .th-wrapper{
justify-content: flex-start;
}`

**Comment by Hiroshana** [comment]
Thank you Boff. It works.

let me know your next release with new features.

Regards
Hiroshana
