### ISSUE TITLE
Server Side Render

### ISSUE THREAD

**Issue by Hiroshana** [aquilesb/v-datatable-light#25]
Hello, 

I am having issue working with server-side data and showing in tables.

can you explain me how we can use server side data please ?

Regards
Hiroshana

**Comment by aquilesb** [comment]
Hi, can you create a codesandbox project to show me which problems are you facing with the library?
I'm happy to help you.

**Comment by Hiroshana** [comment]
Thanks, Boff, after three days I just sort out the issue. Thank you again trying to help me.

Hiroshana

**Comment by aquilesb** [comment]
I'm glad you found the problem.
