### ISSUE TITLE
Sorting Datatable

### ISSUE THREAD

**Issue by yunusffz** [aquilesb/v-datatable-light#28]
Issue when sort, not sort all row data. But only sort data appear in one page. In other page data not sorted

**Comment by aquilesb** [comment]
Can you create an example on codepen showing this behaviour?

**Comment by aldanux** [comment]
@aquilesb - You can see the behavior on your own [demo](https://codepen.io/aquilesb/pen/wVaBPv) in CodePen

**Comment by aquilesb** [comment]
I will take a look and return

**Comment by aquilesb** [comment]
yes the example is wrong, I am not using the sorted data when I change page, I will fix it soon

**Comment by aquilesb** [comment]
The example in Codepen is fixed (soon I will commit these changes on the example on github), it is not a bug in the lib, it was a bad implementation of it in the example. The lib does not change the data by itself, it is only responsible for display and emits events.
