### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by Hiroshana** [aquilesb/v-datatable-light#30]
Hello, 
I am using 0.81 version and seen something issues on pagination.
1)	Ex, In your all the examples three (https://codepen.io/aquilesb/pen/wVaBPv), you are using 21 records and if we select 10 records per page, it shows first page -10, second page 10 and third should be 1, but here last page doesn’t show. Only show 2 pages.

Appreciate your support and advice on this regard.

Thank you
Hiroshana

**Comment by aquilesb** [comment]
Hi @Hiroshana,
The lib is not responsible for the pagination, only to display it.  It was a bug in the demo, I already fixed it in the codepen you mentioned.
Thanks
