### ISSUE TITLE
Responsiveness when the width is narrow?

### ISSUE THREAD

**Issue by paulrosen** [aquilesb/v-datatable-light#33]
This doesn't look supported but I'll ask in case I missed it - is there a way to make this responsive for mobile? What I'm envisioning is that below a certain width the display changes to individual cards instead of rows and the data appears with the column name.

**Comment by aquilesb** [comment]
Hey @paulrosen, the lib so far does not have anything that changes the result HTML depending on the resolution. All it does is gives the possibility to add classes to change that by CSS.
I have used some CSS approaches to deal with that. Here you can find as well, I hope this help you.
[https://elvery.net/demo/responsive-tables/#flip-scroll](https://elvery.net/demo/responsive-tables/#flip-scroll)
[https://dbushell.com/2016/03/04/css-only-responsive-tables/](https://dbushell.com/2016/03/04/css-only-responsive-tables/)

**Comment by paulrosen** [comment]
That's an interesting idea - to flip the x and y axis when it is narrow. I wanted to turn the look into a list of "cards" when it is narrow and started experimenting with css after posting this. I think it is actually easier than I thought it would be - starting with `tr { display: flex}` and `td { display: block }` gets the general idea. Then adding `td:nth-child(1):before { content: "name" }` even puts the column names in each card.

So it looks like this project will work for me - I like how small it is. I am not creating a spreadsheet.

Thanks so much!
