### ISSUE TITLE
Hide headers

### ISSUE THREAD

**Issue by mawieutc** [aquilesb/v-datatable-light#9]
Hi, 
Could it be possible to hide headers?
Thanks !

**Comment by aquilesb** [comment]
You can do that with CSS

**Comment by mawieutc** [comment]
Thanks aquilesb, indeed it works well.
if(hideHeaders){
    css_pers['thead'] = 'thead-hidden';
 }
.thead-hidden{
    visibility: hidden;
}
I am also wondering if it would be possible to add special content to the columns, such as images or links?

**Comment by aquilesb** [comment]
Yes, it is possible to add any type of element you wish, to achieve that you have to use slots inside the `<Datatable>` tag. 
You can see it on this [example](https://codesandbox.io/s/o5qlyw3l26) 

On the `headerFields`  list you have to add an action string (eg `__slot:actions:myActionID`) and inside the `<Datatable>` tag you can define which element you wish and set the `slot` attribute to the action ID chosen, in this example `myActionID`.

**Comment by mawieutc** [comment]
Thank you so much, it works perfectly! I am just trying to add headers now :)
